FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

# Install dotnet-ef tools
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Copy project files
COPY . .

# Restore dependencies
RUN dotnet restore

# Keep container running
ENTRYPOINT ["dotnet", "watch", "run", "--project", "TaskManagement.API/TaskManagement.API.csproj", "--urls", "http://+:80"]